services:
  - type: web
    name: ml-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run load_model.py --server.port $PORT --server.address 0.0.0.0
    repo: https://github.com/Parthsawant1298/ml-project-1743099371.git
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.7"  # Full patch version
      - key: MODEL_FILE
        value: best_model.pkl
